"""Initial migration

Revision ID: 8e42e0ffe5b9
Revises: 
Create Date: 2026-06-17 23:10:51.432795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8e42e0ffe5b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('road_closure', sa.Boolean(), nullable=True),
    sa.Column('predicted_severity', sa.Float(), nullable=True),
    sa.Column('predicted_resolution_time_mins', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_traffic_events_location', 'traffic_events', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_traffic_events_event_type'), 'traffic_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_traffic_events_id'), 'traffic_events', ['id'], unique=False)
    op.create_table('simulated_interventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('strategy_name', sa.String(), nullable=True),
    sa.Column('officers_deployed', sa.Integer(), nullable=True),
    sa.Column('barricades_deployed', sa.Integer(), nullable=True),
    sa.Column('impact_reduction_pct', sa.Float(), nullable=True),
    sa.Column('ties_score', sa.Float(), nullable=True),
    sa.Column('is_final_selection', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['traffic_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulated_interventions_id'), 'simulated_interventions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulated_interventions_id'), table_name='simulated_interventions')
    op.drop_table('simulated_interventions')
    op.drop_index(op.f('ix_traffic_events_id'), table_name='traffic_events')
    op.drop_index(op.f('ix_traffic_events_event_type'), table_name='traffic_events')
    op.drop_index('idx_traffic_events_location', table_name='traffic_events', postgresql_using='gist')
    op.drop_table('traffic_events')
    # ### end Alembic commands ###
