"""sqlite_init

Revision ID: ac31f97df29f
Revises: 
Create Date: 2026-06-18 19:42:00.435799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac31f97df29f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulated_interventions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('strategy_name', sa.String(), nullable=True),
    sa.Column('officers_deployed', sa.Integer(), nullable=True),
    sa.Column('barricades_deployed', sa.Integer(), nullable=True),
    sa.Column('impact_reduction_pct', sa.Float(), nullable=True),
    sa.Column('ties_score', sa.Float(), nullable=True),
    sa.Column('is_final_selection', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['traffic_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulated_interventions_id'), 'simulated_interventions', ['id'], unique=False)
    op.alter_column('traffic_events', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('traffic_events', 'location',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_traffic_events_event_type'), 'traffic_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_traffic_events_id'), 'traffic_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_events_id'), table_name='traffic_events')
    op.drop_index(op.f('ix_traffic_events_event_type'), table_name='traffic_events')
    op.alter_column('traffic_events', 'location',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('traffic_events', 'id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_simulated_interventions_id'), table_name='simulated_interventions')
    op.drop_table('simulated_interventions')
    # ### end Alembic commands ###
